name: Validate Mono versions
on:
  workflow_dispatch:

jobs:
  mono-125-mono-1:
    name: ToDo Mono 6.12.0.125 Nuget restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-140-nuget-1:
    name: ToDo Mono 6.12.0.140 Nuget restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Update Nuget version
      run: bash ./update-nuget.sh
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-140-nuget-2:
    name: ToDo Mono 6.12.0.140 Nuget restore 2
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-147-nuget-1:
    name: ToDo Mono 6.12.0.147 Nuget restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Update Nuget version
      run: bash ./update-nuget.sh
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-147-nuget-2:
    name: ToDo Mono 6.12.0.147 Nuget restore 2
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln
