name: Validate Mono versions
on:
  workflow_dispatch:

jobs:
  mono-125-mono-1:
    name: Mono 6.12.0.140
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-140-nuget-1:
    name: Mono 6.12.0.140 update Nuget version
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln
