name: Validate Mono versions
on:
  workflow_dispatch:

jobs:
  mono-current:
    name: Mono current (nuget)
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-current-msbuild:
    name: Mono current (msbuild)
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: MSbuild restore
      run: msbuild /t:restore ./Todo/Todo.sln

  mono-140-nuget:
    name: Mono 6.12.0.140 (nuget)
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-147-nuget:
    name: Mono 6.12.0.147 (nuget)
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-147-msbuild:
    name: Mono 6.12.0.147 (msbuild)
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - name: Nuget version
      run: nuget help
    - name: MSbuild restore
      run: msbuild /t:restore ./Todo/Todo.sln
