name: Validate Mono versions
on:
  workflow_dispatch:

jobs:
  mono-125-mono-1:
    name: Mono 6.12.0.140
    runs-on: [self-hosted, macOS, x64]
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Nuget version
      run: nuget help
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln
